export interface SpriteGrid {
  size: number
  pixels: string[]
}

export interface SpriteAnimation {
  frames: SpriteGrid[]
  frameDuration: number  // ms per frame
}

function px(size: number, grid: string, map: Record<string, string>): string[] {
  return grid
    .replace(/\s/g, '')
    .slice(0, size * size)
    .split('')
    .map((c) => (c === '.' ? '' : (map[c] ?? '')))
}

// ── Global color shortcuts (for llama, critters, static sprites) ──
const B = '#e8d09a'  // llama body tan
const S = '#7a5c38'  // shadow / dark outline
const H = '#f0e4bc'  // highlight / face
const G = '#c0a060'  // gold accents
const W = '#ffffff'  // white
const F = '#8c6a3f'  // forge brown
const Y = '#f5c518'  // yellow (star / bird)
const T = '#333333'  // terminal dark
const N = '#4caf50'  // terminal green

// ── Static sprites ───────────────────────────────────────────────

export const SPRITE_DOOR: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    SSSSSSSS
    SSGGGGSS
    SGSSSSGS
    SS....SS
    SS....SS
    SS....SS
    SS....SS
    SSSSSSSS
  `, { S, G }),
}

export const SPRITE_GATE: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    GGGGGGGG
    G.G.G.G.
    G.G.G.G.
    GGGGGGGG
    G.G.G.G.
    G.G.G.G.
    G.G.G.G.
    GGGGGGGG
  `, { G: '#888888' }),
}

export const SPRITE_PORTAL: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    TTTTTTT.
    TNNNNNT.
    TNN.N.T.
    TNNNNNT.
    TTTTTTT.
    ..TTT...
    .TTTTT..
    ........
  `, { T, N }),
}

export const SPRITE_DECO_LLAMA: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    ..BB....
    .BB.....
    BBBBB...
    BBBBB...
    B.B.B...
    S.S.S...
    ........
    ........
  `, { B, S }),
}

// ── Player walk animation — 16×16 chibi, 2 frames 300ms ─────────
// Blue jacket, red cap, tan skin, dark pants, green shoes (Ness style)

const PR = '#d04828'  // red cap
const PH = '#f0d898'  // face/skin
const PE = '#2a1a0a'  // eye pupil
const PJ = '#4a88d0'  // blue jacket
const PP = '#3060a0'  // dark pants
const PS = '#4a3020'  // outline shadow
const PG = '#3a7838'  // green shoes

export const SPRITE_PLAYER_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 16,
      pixels: px(16, `
        ....RRRRRRRR....
        ...RRRRRRRRRR...
        ..RRRRRRRRRRRR..
        ...HHHHHHHHHH...
        ...HHHeHHeHHH...
        ...HHHHHHHHHH...
        ....SHHHHHHS....
        ...SJJJJJJJJS...
        ...SJJJJJJJJS...
        ...SJJJJJJJJS...
        ....PPPPPPPP....
        ....PPP..PPP....
        ....PPP..PPP....
        ....PPP..PPP....
        ....GGG..GGG....
        ................
      `, { R: PR, H: PH, e: PE, J: PJ, P: PP, S: PS, G: PG }),
    },
    {
      size: 16,
      pixels: px(16, `
        ....RRRRRRRR....
        ...RRRRRRRRRR...
        ..RRRRRRRRRRRR..
        ...HHHHHHHHHH...
        ...HHHeHHeHHH...
        ...HHHHHHHHHH...
        ....SHHHHHHS....
        ...SJJJJJJJJS...
        ...SJJJJJJJJS...
        ...SJJJJJJJJS...
        ....PPPPPPPP....
        ...PPP....PPP...
        ...PPP....PPP...
        ...PPP....PPP...
        ...GGG....GGG...
        ................
      `, { R: PR, H: PH, e: PE, J: PJ, P: PP, S: PS, G: PG }),
    },
  ],
  frameDuration: 300,
}

// ── NPC animations — 16×16, auto-bob frame ──────────────────────
// Frame 0: normal. Frame 1: shift down 1 row (idle bob).

function makeNPCAnimation(gridStr: string, map: Record<string, string>): SpriteAnimation {
  const size = 16
  const cleaned = gridStr.replace(/\s/g, '').slice(0, size * size)
  const emptyRow = '.'.repeat(size)
  const f1 = emptyRow + cleaned.slice(0, size * (size - 1))
  const mapPx = (c: string) => (c === '.' ? '' : (map[c] ?? ''))
  return {
    frames: [
      { size, pixels: cleaned.split('').map(mapPx) },
      { size, pixels: f1.split('').map(mapPx) },
    ],
    frameDuration: 800,
  }
}

const FACE = '#f0d898'
const EYE  = '#2a1a0a'

// Elder — gold hat, warm golden face, purple robe
export const SPRITE_NPC_ELDER_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....GGGGGGGG....
  ...GGGGGGGGGG...
  ..GGGGGGGGGGGG..
  ...FFFFFFFFFF...
  ...FFFeFFeFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ...PPPPPPPPPP...
  ....PPP..PPP....
  ....PPP..PPP....
  ....PPP..PPP....
  ....ttt..ttt....
  ................
`, { G: '#c0a030', F: '#f0d080', e: EYE, P: '#7840a0', D: '#4a2060', t: '#8a6840' })

// Pip — yellow pigtails, pink dress, blue shoes
export const SPRITE_NPC_PIP_ANIM: SpriteAnimation = makeNPCAnimation(`
  Y...YYYYYY...Y..
  YY.YYYYYYYY.YY..
  .YYYYYYYYYY.....
  ...FFFFFFFFFF...
  ...FFFeFFeFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ...PPPPPPPPPP...
  ....PPP..PPP....
  ....PPP..PPP....
  ....PPP..PPP....
  ....bbb..bbb....
  ................
`, { Y: '#f0d840', F: FACE, e: EYE, P: '#e060a0', D: '#801850', b: '#2060d0' })

// Smith — dark brown hair, orange forge overalls, brown boots
export const SPRITE_NPC_SMITH_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....WWWWWWWW....
  ...WWWWWWWWWW...
  ..WWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFFeFFeFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DOOOOOOOOOOD..
  ..DOOOOOOOOOOD..
  ..DOOOOOOOOOOD..
  ...OOOOOOOOOO...
  ....OOO..OOO....
  ....OOO..OOO....
  ....OOO..OOO....
  ....bbb..bbb....
  ................
`, { W: '#3a2010', F: FACE, e: EYE, O: '#d85020', D: '#6a2010', b: '#5a3010' })

// Artificer — blue hair, cyan tech suit, goggle eyes, dark boots
export const SPRITE_NPC_ARTIFICER_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....WWWWWWWW....
  ...WWWWWWWWWW...
  ..WWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFFoFFoFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DCCCCCCCCCCD..
  ..DCCCCCCCCCCD..
  ..DCCCCCCCCCCD..
  ...CCCCCCCCCC...
  ....CCC..CCC....
  ....CCC..CCC....
  ....CCC..CCC....
  ....ddd..ddd....
  ................
`, { W: '#304888', F: FACE, o: '#40a0f0', C: '#4070c0', D: '#182848', d: '#102040' })

// Oracle — purple hair, violet robe, mauve boots
export const SPRITE_NPC_ORACLE_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....WWWWWWWW....
  ...WWWWWWWWWW...
  ..WWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFFeFFeFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DVVVVVVVVVVD..
  ..DVVVVVVVVVVD..
  ..DVVVVVVVVVVD..
  ...VVVVVVVVVV...
  ....VVV..VVV....
  ....VVV..VVV....
  ....VVV..VVV....
  ....mmm..mmm....
  ................
`, { W: '#7040a0', F: FACE, e: EYE, V: '#8050c0', D: '#301840', m: '#5a2880' })

// Vector — golden hair, sky-blue outfit, navy boots
export const SPRITE_NPC_VECTOR_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....WWWWWWWW....
  ...WWWWWWWWWW...
  ..WWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFFeFFeFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DAAAAAAAAAAD..
  ..DAAAAAAAAAAD..
  ..DAAAAAAAAAAD..
  ...AAAAAAAAAA...
  ....AAA..AAA....
  ....AAA..AAA....
  ....AAA..AAA....
  ....nnn..nnn....
  ................
`, { W: '#f0c820', F: FACE, e: EYE, A: '#30a0e0', D: '#184870', n: '#102848' })

// Architect — teal hair, green outfit, warm brown boots
export const SPRITE_NPC_ARCHITECT_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....WWWWWWWW....
  ...WWWWWWWWWW...
  ..WWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFFeFFeFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DGGGGGGGGGGD..
  ..DGGGGGGGGGGD..
  ..DGGGGGGGGGGD..
  ...GGGGGGGGGG...
  ....GGG..GGG....
  ....GGG..GGG....
  ....GGG..GGG....
  ....www..www....
  ................
`, { W: '#208060', F: FACE, e: EYE, G: '#40b080', D: '#103828', w: '#6a4020' })

// Keeper — indigo hair, indigo-purple outfit, plum boots
export const SPRITE_NPC_KEEPER_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....WWWWWWWW....
  ...WWWWWWWWWW...
  ..WWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFFeFFeFFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DIIIIIIIIIID..
  ..DIIIIIIIIIID..
  ..DIIIIIIIIIID..
  ...IIIIIIIIII...
  ....III..III....
  ....III..III....
  ....III..III....
  ....ppp..ppp....
  ................
`, { W: '#504090', F: FACE, e: EYE, I: '#6050a0', D: '#201838', p: '#401860' })

// ── Critter animations — 8×8, 2 frames 300ms ────────────────────

export const SPRITE_RABBIT_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        .HH.....
        HHHH....
        HWWH....
        HHHH....
        .HHH....
        .HH.....
        .H.H....
        .S.S....
      `, { H, W, S }),
    },
    {
      size: 8,
      pixels: px(8, `
        HH......
        HHHH....
        HWWH....
        .HHHH...
        ..HHH...
        ...HH...
        ...HS...
        ....S...
      `, { H, W, S }),
    },
  ],
  frameDuration: 300,
}

export const SPRITE_BIRD_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        ........
        ..YYY...
        .YYYYY..
        .YWYY...
        ..YSY...
        .Y.Y....
        ........
        ........
      `, { Y, W, S }),
    },
    {
      size: 8,
      pixels: px(8, `
        .Y...Y..
        YYYYYYY.
        .YWYYY..
        ..YSY...
        ...Y....
        ........
        ........
        ........
      `, { Y, W, S }),
    },
  ],
  frameDuration: 300,
}

export const SPRITE_SQUIRREL_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        ...FFF..
        ..FFFF..
        .FWFFF..
        .FFFFF..
        HFFFFFF.
        HFFFFF..
        .F..F...
        .S..S...
      `, { F, W, H, S }),
    },
    {
      size: 8,
      pixels: px(8, `
        ....FFF.
        ...FFFF.
        ..FWFFF.
        ..FFFFF.
        .HFFFFF.
        HFFFFF..
        .SF.....
        ..S.....
      `, { F, W, H, S }),
    },
  ],
  frameDuration: 300,
}

export const SPRITE_BUTTERFLY_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        CC.CC...
        CCCCC...
        YCYYY...
        .OOO....
        YCYYY...
        CCCCC...
        CC.CC...
        ........
      `, { C: '#a0e0ff', Y, O: '#7a4a8c' }),
    },
    {
      size: 8,
      pixels: px(8, `
        ........
        .C.C....
        CCYCC...
        .OOO....
        CCYCC...
        .C.C....
        ........
        ........
      `, { C: '#a0e0ff', Y, O: '#7a4a8c' }),
    },
  ],
  frameDuration: 300,
}

// ── Title screen llama — 20×20 static ───────────────────────────

export const TITLE_LLAMA: SpriteGrid = {
  size: 20,
  pixels: px(20, `
    .............B.B....
    ............BB.BB...
    ............BBBBB...
    ............BW.SB...
    ............BBBBB...
    ...........BBBBB....
    ..........BBBBB.....
    .........BBBBB......
    ......BBBBBBBBBBBB..
    .....HBBBBBBBBBBBBB.
    .....BBBBBBBBBBBBB..
    .....BBBBBBBBBBBBB..
    .....SSBBBBBBBBBBBS.
    ......SSBBBBBBBBBS..
    .....B.B.........B.B
    .....B.B.........B.B
    .....B.B.........B.B
    .....B.B.........B.B
    .....S.S.........S.S
    ....................
  `, { B, S, H, W }),
}
