export interface SpriteGrid {
  size: number
  pixels: string[]
}

export interface SpriteAnimation {
  frames: SpriteGrid[]
  frameDuration: number  // ms per frame
}

function px(size: number, grid: string, map: Record<string, string>): string[] {
  return grid
    .replace(/\s/g, '')
    .slice(0, size * size)
    .split('')
    .map((c) => (c === '.' ? '' : (map[c] ?? '')))
}

// ── Global color shortcuts (llama, critters, static sprites) ──
const B = '#e8d09a'
const S = '#7a5c38'
const H = '#f0e4bc'
const G = '#c0a060'
const W = '#ffffff'
const F = '#8c6a3f'
const Y = '#f5c518'
const T = '#333333'
const N = '#4caf50'

// ── Static sprites ───────────────────────────────────────────────

export const SPRITE_DOOR: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    SSSSSSSS
    SSGGGGSS
    SGSSSSGS
    SS....SS
    SS....SS
    SS....SS
    SS....SS
    SSSSSSSS
  `, { S, G }),
}

export const SPRITE_GATE: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    GGGGGGGG
    G.G.G.G.
    G.G.G.G.
    GGGGGGGG
    G.G.G.G.
    G.G.G.G.
    G.G.G.G.
    GGGGGGGG
  `, { G: '#888888' }),
}

export const SPRITE_PORTAL: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    TTTTTTT.
    TNNNNNT.
    TNN.N.T.
    TNNNNNT.
    TTTTTTT.
    ..TTT...
    .TTTTT..
    ........
  `, { T, N }),
}

export const SPRITE_DECO_LLAMA: SpriteGrid = {
  size: 8,
  pixels: px(8, `
    ..BB....
    .BB.....
    BBBBB...
    BBBBB...
    B.B.B...
    S.S.S...
    ........
    ........
  `, { B, S }),
}

// ── Player — 16×16, Ness-inspired Earthbound chibi ───────────────
// Red cap with dark hair peeking out at sides.
// Eyebrows (b), white sclera eyes (e=pupil, w=white), nose (n), mouth (m).

const PR = '#d04828'  // red cap + red shoes (Ness-authentic)
const PH = '#f0d898'  // face skin
const PD = '#2a1808'  // dark hair under cap
const PB = '#3a2808'  // eyebrow / face shadow
const PE = '#2a1a0a'  // eye pupil
const PW = '#ffffff'  // eye white sclera
const PY = '#f0e040'  // yellow shirt stripe (Ness stripe)
const PJ = '#4a88d0'  // blue shirt stripe (Ness stripe)
const PP = '#3060a0'  // dark pants
const PS = '#4a3020'  // outline shadow

export const SPRITE_PLAYER_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 16,
      pixels: px(16, `
        ....RRRRRRRR....
        ...RRRRRRRRRR...
        .DDRRRRRRRRRDD..
        ...HHHHHHHHHH...
        ...HHbHHHHbHH...
        ...HHewHHweHH...
        ....HHnHHHHH....
        ....HHmHHmHH....
        ...SYYYYYYYYS...
        ...SJJJJJJJJS...
        ...SYYYYYYYYS...
        ....PPPPPPPP....
        ....PPP..PPP....
        ....PPP..PPP....
        ....GGG..GGG....
        ................
      `, { R: PR, H: PH, D: PD, b: PB, e: PE, w: PW, n: PB, m: PE, Y: PY, J: PJ, P: PP, S: PS, G: PR }),
    },
    {
      size: 16,
      pixels: px(16, `
        ....RRRRRRRR....
        ...RRRRRRRRRR...
        .DDRRRRRRRRRDD..
        ...HHHHHHHHHH...
        ...HHbHHHHbHH...
        ...HHewHHweHH...
        ....HHnHHHHH....
        ....HHmHHmHH....
        ...SYYYYYYYYS...
        ...SJJJJJJJJS...
        ...SYYYYYYYYS...
        ....PPPPPPPP....
        ...PPP....PPP...
        ...PPP....PPP...
        ...GGG....GGG...
        ................
      `, { R: PR, H: PH, D: PD, b: PB, e: PE, w: PW, n: PB, m: PE, Y: PY, J: PJ, P: PP, S: PS, G: PR }),
    },
  ],
  frameDuration: 300,
}

// ── NPC animations — 16×16, auto-bob frame ──────────────────────
// Face rows: top, eyebrows (q=dark), eyes (e=pupil, w=white), lower face, chin.

function makeNPCAnimation(gridStr: string, map: Record<string, string>): SpriteAnimation {
  const size = 16
  const cleaned = gridStr.replace(/\s/g, '').slice(0, size * size)
  const emptyRow = '.'.repeat(size)
  const f1 = emptyRow + cleaned.slice(0, size * (size - 1))
  const mapPx = (c: string) => (c === '.' ? '' : (map[c] ?? ''))
  return {
    frames: [
      { size, pixels: cleaned.split('').map(mapPx) },
      { size, pixels: f1.split('').map(mapPx) },
    ],
    frameDuration: 800,
  }
}

const FACE = '#f0d898'
const EYE  = '#2a1a0a'
const ESCLERA = '#ffffff'

// Elder — tall gold hat, warm golden face, purple robe
// Dignified, symmetric hat — no hair spikes
export const SPRITE_NPC_ELDER_ANIM: SpriteAnimation = makeNPCAnimation(`
  ....GGGGGGGG....
  ...GGGGGGGGGG...
  ..GGGGGGGGGGGG..
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFewFFweFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....ttt..ttt....
  ................
`, { G: '#c0a030', F: '#f0d080', q: EYE, e: EYE, w: ESCLERA, P: '#7840a0', D: '#4a2060', L: '#7840a0', t: '#8a6840' })

// Pip — yellow pigtails at sides, pink dress, blue shoes
export const SPRITE_NPC_PIP_ANIM: SpriteAnimation = makeNPCAnimation(`
  YY.YYYYYY.YY....
  Y..YYYYYY..Y....
  .YYYYYYYYYY.....
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFewFFweFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ..DPPPPPPPPPPD..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....bbb..bbb....
  ................
`, { Y: '#f0d840', F: FACE, q: EYE, e: EYE, w: ESCLERA, P: '#e060a0', D: '#801850', L: '#e060a0', b: '#2060d0' })

// Smith — charcoal spiky hair, orange forge overalls, brown boots
export const SPRITE_NPC_SMITH_ANIM: SpriteAnimation = makeNPCAnimation(`
  ..W.WWWWWW.W....
  .WWWWWWWWWWW....
  WWWWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFewFFweFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DOOOOOOOOOOD..
  ..DOOOOOOOOOOD..
  ..DOOOOOOOOOOD..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....bbb..bbb....
  ................
`, { W: '#484848', F: FACE, q: EYE, e: EYE, w: ESCLERA, O: '#d85020', D: '#6a2010', L: '#d85020', b: '#5a3010' })

// Artificer — blue angled hair, cyan tech suit, goggle eyes
export const SPRITE_NPC_ARTIFICER_ANIM: SpriteAnimation = makeNPCAnimation(`
  .....WWWWWWWW...
  ...WWWWWWWWWW...
  .WWWWWWWWWWWW...
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFooFFooFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DCCCCCCCCCCD..
  ..DCCCCCCCCCCD..
  ..DCCCCCCCCCCD..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....ddd..ddd....
  ................
`, { W: '#304888', F: FACE, q: EYE, o: '#40a0f0', C: '#4070c0', D: '#182848', L: '#4070c0', d: '#102040' })

// Oracle — purple flowing hair (wider/deeper), violet robe
export const SPRITE_NPC_ORACLE_ANIM: SpriteAnimation = makeNPCAnimation(`
  .WW.WWWWWW.WW...
  WWWWWWWWWWWWWW..
  WWWWWWWWWWWWWW..
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFewFFweFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DVVVVVVVVVVD..
  ..DVVVVVVVVVVD..
  ..DVVVVVVVVVVD..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....mmm..mmm....
  ................
`, { W: '#7040a0', F: FACE, q: EYE, e: EYE, w: ESCLERA, V: '#8050c0', D: '#301840', L: '#8050c0', m: '#5a2880' })

// Vector — spiky golden hair, sky-blue outfit, navy boots
export const SPRITE_NPC_VECTOR_ANIM: SpriteAnimation = makeNPCAnimation(`
  ...W..WWWWWWW...
  ..WWWWWWWWWWW...
  .WWWWWWWWWWWW...
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFewFFweFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DAAAAAAAAAAD..
  ..DAAAAAAAAAAD..
  ..DAAAAAAAAAAD..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....nnn..nnn....
  ................
`, { W: '#f0c820', F: FACE, q: EYE, e: EYE, w: ESCLERA, A: '#30a0e0', D: '#184870', L: '#30a0e0', n: '#102848' })

// Architect — teal swept hair, green outfit, warm boots
export const SPRITE_NPC_ARCHITECT_ANIM: SpriteAnimation = makeNPCAnimation(`
  ........WWWWWW..
  ...WWWWWWWWWW...
  .WWWWWWWWWWWW...
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFewFFweFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DGGGGGGGGGGD..
  ..DGGGGGGGGGGD..
  ..DGGGGGGGGGGD..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....vvv..vvv....
  ................
`, { W: '#208060', F: FACE, q: EYE, e: EYE, w: ESCLERA, G: '#40b080', D: '#103828', L: '#40b080', v: '#6a4020' })

// Keeper — indigo hair with center part, indigo outfit, plum boots
export const SPRITE_NPC_KEEPER_ANIM: SpriteAnimation = makeNPCAnimation(`
  .WW...WW...WW...
  .WWWWWWWWWWWW...
  .WWWWWWWWWWWW...
  ...FFFFFFFFFF...
  ...FFqFFFFqFF...
  ...FFewFFweFF...
  ...FFFFFFFFFF...
  ....FFFFFFFF....
  ..DIIIIIIIIIID..
  ..DIIIIIIIIIID..
  ..DIIIIIIIIIID..
  ....LLL..LLL....
  ....LLL..LLL....
  ....LLL..LLL....
  ....ppp..ppp....
  ................
`, { W: '#504090', F: FACE, q: EYE, e: EYE, w: ESCLERA, I: '#6050a0', D: '#201838', L: '#6050a0', p: '#401860' })

// ── Critter animations — 8×8 ─────────────────────────────────────

export const SPRITE_RABBIT_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        .e..e...
        .e..e...
        eeeee...
        eWeee...
        .eeee...
        .eePe...
        .e..e...
        .s..s...
      `, { e: '#e8e8e8', W: '#2a1a0a', P: '#f090a0', s: '#b0b0b0' }),
    },
    {
      size: 8,
      pixels: px(8, `
        .e..e...
        .e..e...
        eeeee...
        eWeee...
        .eeee...
        .eePe...
        .ee.e...
        .s...s..
      `, { e: '#e8e8e8', W: '#2a1a0a', P: '#f090a0', s: '#b0b0b0' }),
    },
  ],
  frameDuration: 400,
}

export const SPRITE_BIRD_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        ........
        ..bbb...
        .bbbbb..
        .bWbob..
        ..bbb...
        ..b.b...
        ........
        ........
      `, { b: '#4090d8', W: '#ffffff', o: '#f0c030' }),
    },
    {
      size: 8,
      pixels: px(8, `
        .b...b..
        bbbbbbb.
        .bWbob..
        ..bbb...
        ..b.b...
        ........
        ........
        ........
      `, { b: '#4090d8', W: '#ffffff', o: '#f0c030' }),
    },
  ],
  frameDuration: 250,
}

export const SPRITE_SQUIRREL_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        ...ttt..
        ..ttttt.
        .tWtttt.
        .ttttt..
        qtttttt.
        qttttq..
        .t..t...
        .d..d...
      `, { t: '#c86820', W: '#2a1a0a', q: '#e09040', d: '#5a3010' }),
    },
    {
      size: 8,
      pixels: px(8, `
        ....ttt.
        ...ttttt
        ..tWtttt
        ..ttttt.
        .qtttttt
        qttttq..
        .dt.....
        ..d.....
      `, { t: '#c86820', W: '#2a1a0a', q: '#e09040', d: '#5a3010' }),
    },
  ],
  frameDuration: 300,
}

export const SPRITE_BUTTERFLY_ANIM: SpriteAnimation = {
  frames: [
    {
      size: 8,
      pixels: px(8, `
        ww.ww...
        wwwww...
        nwnww...
        .ooo....
        nwnww...
        wwwww...
        ww.ww...
        ........
      `, { w: '#f08020', n: '#1a1a1a', o: '#f8e040' }),
    },
    {
      size: 8,
      pixels: px(8, `
        ........
        .w.w....
        wwnww...
        .ooo....
        wwnww...
        .w.w....
        ........
        ........
      `, { w: '#f08020', n: '#1a1a1a', o: '#f8e040' }),
    },
  ],
  frameDuration: 250,
}

// ── Title screen llama — 20×20 static ───────────────────────────

export const TITLE_LLAMA: SpriteGrid = {
  size: 20,
  pixels: px(20, `
    .............B.B....
    ............BB.BB...
    ............BBBBB...
    ............BW.SB...
    ............BBBBB...
    ...........BBBBB....
    ..........BBBBB.....
    .........BBBBB......
    ......BBBBBBBBBBBB..
    .....HBBBBBBBBBBBBB.
    .....BBBBBBBBBBBBB..
    .....BBBBBBBBBBBBB..
    .....SSBBBBBBBBBBBS.
    ......SSBBBBBBBBBS..
    .....B.B.........B.B
    .....B.B.........B.B
    .....B.B.........B.B
    .....B.B.........B.B
    .....S.S.........S.S
    ....................
  `, { B, S, H, W }),
}
